version: '3'
services:
  backend:
    image: node:17
    working_dir: /app
    command: "yarn start"
    volumes:
      - ./backend:/app
      - log_data:/app/data
    tty: true
    user: '1000'
    ports: 
      - 9000:9000
  frontend:
    image: node:17
    working_dir: /app
    command: yarn start
    volumes:
      - ./frontend:/app
    tty: true
    user: '1000'
    ports:
      - 8900:8900

volumes:
  log_data: